# Generated by Django 2.0.7 on 2018-08-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0002_auto_20180803_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='relation_to_guardians',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Relation_to_guardians'),
        ),
    ]
