# Generated by Django 2.0.7 on 2018-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0003_auto_20180804_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_modify_after_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_print_registration_form',
            field=models.BooleanField(default=False),
        ),
    ]
