# Generated by Django 2.0.7 on 2018-09-09 07:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0005_auto_20180817_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('time', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='date_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='grade',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='pass_mark',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='date_of_passing_on',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='image_sec',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Upload photo'),
        ),
    ]
