# Generated by Django 2.1.1 on 2019-01-14 22:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0006_auto_20180909_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=300)),
                ('IsDefaultAccount', models.BooleanField(blank=True, default=False)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyType', models.CharField(choices=[('1', 'Add balance'), ('2', 'Remove balance')], max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Note', models.TextField(max_length=500)),
                ('IsTransfardBalance', models.BooleanField(blank=True, default=False)),
                ('create_on', models.DateField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(auto_now=True, null=True)),
                ('IsApproved', models.BooleanField(blank=True, default=False)),
                ('approvDate', models.DateTimeField(blank=True, null=True)),
                ('bankBranch', models.CharField(blank=True, max_length=300)),
                ('bankIssueDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date')),
                ('id_no', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_item', models.CharField(blank=True, max_length=300, null=True)),
                ('total', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(auto_now=True, null=True)),
                ('head_no', models.IntegerField(blank=True, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceIncome_institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(auto_now=True, null=True)),
                ('head_no', models.IntegerField(blank=True, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField(max_length=500)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(auto_now=True, null=True)),
                ('bank_accounts', models.ManyToManyField(blank=True, to='bnmc_project.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='CenterManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_start', models.CharField(blank=True, max_length=300, null=True)),
                ('roll_end', models.CharField(blank=True, max_length=300, null=True)),
                ('hall_name', models.CharField(blank=True, max_length=300, null=True)),
                ('room_name', models.CharField(blank=True, max_length=300, null=True)),
                ('center', models.ForeignKey(null=True, on_delete=None, to='bnmc_project.ExamCenter')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationStudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Full name (English)')),
                ('fathers_name', models.CharField(blank=True, max_length=300, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=300, null=True)),
                ('sex', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=12, null=True)),
                ('religions', models.CharField(blank=True, choices=[('1', 'Islam'), ('2', 'Hindu'), ('3', 'Buddhist'), ('4', 'Christian'), ('5', 'Others')], max_length=120, null=True)),
                ('students_mobile_no', models.CharField(max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=300, null=True)),
                ('post_office', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=300, null=True)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(blank=True, null=True)),
                ('publish_result', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.District')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Division')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(blank=True, default=0.0, null=True)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('examStudentInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.ExaminationStudentRegistration')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('fullMarks', models.FloatField(blank=True, default=0.0, null=True)),
                ('passMarks', models.FloatField(blank=True, default=0.0, null=True)),
                ('code', models.CharField(blank=True, max_length=300)),
                ('isMainSubject', models.BooleanField(blank=True, default=False)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(auto_now=True, null=True)),
                ('SubSubjects', models.ManyToManyField(blank=True, to='bnmc_project.ExamSubject', verbose_name='Sub Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Final_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('established_date', models.DateField(blank=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('hospital_address', models.TextField(max_length=500)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntuitionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_nurse', models.BooleanField(blank=True)),
                ('image', models.ImageField(upload_to='institute_profile/')),
                ('employment_type', models.CharField(blank=True, max_length=300)),
                ('designation', models.CharField(blank=True, max_length=300)),
                ('faculty_id', models.CharField(blank=True, max_length=300)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('work_starting_date', models.DateField(blank=True, null=True)),
                ('full_name_english', models.CharField(blank=True, max_length=300, null=True)),
                ('father_name', models.CharField(blank=True, max_length=300, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=300, null=True)),
                ('sex', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=12, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('1', 'Single'), ('2', 'Married'), ('3', 'Widow'), ('4', 'Divorce'), ('5', 'Separated')], max_length=120, null=True)),
                ('national_ID_No', models.CharField(blank=True, max_length=128, null=True)),
                ('students_mobile_no', models.CharField(max_length=200, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=128, null=True)),
                ('village', models.CharField(max_length=300, null=True)),
                ('post_office', models.CharField(max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=300, null=True)),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.District')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Job_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_designation', models.CharField(max_length=50, null=True)),
                ('is_running_job', models.BooleanField()),
                ('job_starting_date', models.DateField(blank=True, null=True)),
                ('job_ending_date', models.DateField(blank=True, null=True)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(blank=True, null=True)),
                ('current_hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='re_new_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('previous_start_date', models.DateField()),
                ('previous_end_date', models.DateField()),
                ('new_start_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Register_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_name', models.CharField(blank=True, max_length=200)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('current_signature', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeatCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('seat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_file/')),
            ],
            options={
                'verbose_name': 'Student Educational Document',
            },
        ),
        migrations.CreateModel(
            name='StudentFileProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TransfarBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Note', models.TextField(blank=True, max_length=500, null=True)),
                ('create_on', models.DateTimeField(blank=True, null=True)),
                ('edit_on', models.DateTimeField(auto_now=True, null=True)),
                ('FromAccount', models.ForeignKey(on_delete=None, related_name='FromAccount', to='bnmc_project.Accounts')),
                ('ToAccount', models.ForeignKey(on_delete=None, related_name='ToAccount', to='bnmc_project.Accounts')),
            ],
        ),
        migrations.RenameField(
            model_name='license_registrations',
            old_name='program_title',
            new_name='exam_title',
        ),
        migrations.RemoveField(
            model_name='license_receive',
            name='program_title',
        ),
        migrations.RemoveField(
            model_name='program',
            name='minimum_grade',
        ),
        migrations.RemoveField(
            model_name='program',
            name='minimum_qualification',
        ),
        migrations.AddField(
            model_name='educationqualification',
            name='institution_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Institution'),
        ),
        migrations.AddField(
            model_name='educationqualification',
            name='level_of_educations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Qualification'),
        ),
        migrations.AddField(
            model_name='educationqualification',
            name='registration_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Upload photo'),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='exam_name',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Exam'),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='license_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='license_registrations_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='license_registrations_receive_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='license_registrations_refference',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.license_registrations'),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='program',
            field=models.ForeignKey(max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Program'),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='registration_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Permission'),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='student_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='hall_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='received_filter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='rool_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='roll number'),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='room_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='student_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='student_registration',
            field=models.ForeignKey(null=True, on_delete=None, to='bnmc_project.Student_Registration', verbose_name='registration'),
        ),
        migrations.AddField(
            model_name='license_registrations',
            name='text_field',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='count_total',
            field=models.FloatField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='total',
            field=models.FloatField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='minimum_grade',
            field=models.FloatField(blank=True, max_length=120, null=True, verbose_name='Minimum Grade'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='program_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Program', verbose_name='program set'),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='license_use',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='locked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='pending',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_result',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='result_for_program',
            field=models.ManyToManyField(blank=True, to='bnmc_project.Program'),
        ),
        migrations.AddField(
            model_name='user',
            name='result_institute',
            field=models.ManyToManyField(blank=True, to='bnmc_project.Institution'),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='CGPA'),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='level_of_education',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Student_Registration', verbose_name='Level Of Education'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.District'),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Full name (Bangla)'),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='last_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Full name (English)'),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='national_ID_No',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Nationality'),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='post_office',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='postal_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='thana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Thana'),
        ),
        migrations.AlterField(
            model_name='license_receive',
            name='village',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='bnmc_project.ExamCenter'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='date_of_passing_on',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.District'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Division'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='first_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Full name (Bangla)'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Full name (English)'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Nationality'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='pass_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='post_office',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='postal_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='registration_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='religions',
            field=models.CharField(blank=True, choices=[('1', 'Islam'), ('2', 'Hindu'), ('3', 'Buddhist'), ('4', 'Christian'), ('5', 'Others')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Thana'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='village',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='programduration',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Program Duration'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardians_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_student_id',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_ID_No',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code_snd',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religions',
            field=models.CharField(choices=[('1', 'Islam'), ('2', 'Hindu'), ('3', 'Buddhist'), ('4', 'Christian'), ('5', 'Others')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='district_snd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='District', to='bnmc_project.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='email_address',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='fathers_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='guardians_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='last_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Full name (English)'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='marital_status',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Married'), ('3', 'Widow'), ('4', 'Divorce'), ('5', 'Separated')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='migration',
            field=models.BooleanField(blank=True, default=False, verbose_name='migrateable'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='migration_approval_bnmc',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='mothers_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='national_ID_No',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Nationality'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='passport_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='post_office',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='post_office_snd',
            field=models.CharField(max_length=300, null=True, verbose_name='Post office'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='postal_code_snd',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='religions',
            field=models.CharField(choices=[('1', 'Islam'), ('2', 'Hindu'), ('3', 'Buddhist'), ('4', 'Christian'), ('5', 'Others')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='same_address',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='session',
            field=models.ForeignKey(limit_choices_to={'is_active': 'True'}, max_length=120, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Session'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='students_mobile_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='thana_snd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thana', to='bnmc_project.Thana', verbose_name='Thana'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='village',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='village_snd',
            field=models.CharField(max_length=300, null=True, verbose_name='Village'),
        ),
        migrations.AddField(
            model_name='studentfileprogram',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Program'),
        ),
        migrations.AddField(
            model_name='student_file',
            name='student_file_program',
            field=models.ForeignKey(null=True, on_delete=None, to='bnmc_project.StudentFileProgram'),
        ),
        migrations.AddField(
            model_name='student_file',
            name='student_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Student_Registration'),
        ),
        migrations.AddField(
            model_name='seatcapacity',
            name='institiution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Institution'),
        ),
        migrations.AddField(
            model_name='seatcapacity',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Program'),
        ),
        migrations.AddField(
            model_name='re_new_history',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.license_receive'),
        ),
        migrations.AddField(
            model_name='re_new_history',
            name='renew_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_history',
            name='license_receive_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.license_receive'),
        ),
        migrations.AddField(
            model_name='job_history',
            name='license_registration_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.license_registrations'),
        ),
        migrations.AddField(
            model_name='job_history',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Student'),
        ),
        migrations.AddField(
            model_name='intuitionprofile',
            name='institute_name',
            field=models.ForeignKey(null=True, on_delete=None, to='bnmc_project.Institution'),
        ),
        migrations.AddField(
            model_name='intuitionprofile',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Nationality'),
        ),
        migrations.AddField(
            model_name='intuitionprofile',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Student'),
        ),
        migrations.AddField(
            model_name='intuitionprofile',
            name='thana',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Thana'),
        ),
        migrations.AddField(
            model_name='final_exam',
            name='program',
            field=models.ForeignKey(null=True, on_delete=None, to='bnmc_project.Program'),
        ),
        migrations.AddField(
            model_name='final_exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='bnmc_project.ExamSubject'),
        ),
        migrations.AddField(
            model_name='final_exam',
            name='year',
            field=models.ForeignKey(null=True, on_delete=None, to='bnmc_project.ExamYear'),
        ),
        migrations.AddField(
            model_name='examresultdetails',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.ExamSubject'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Final_exam'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=None, to='bnmc_project.Institution'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Nationality'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='program',
            field=models.ForeignKey(on_delete=None, to='bnmc_project.Program'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Permission'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='student_registration',
            field=models.ForeignKey(on_delete=None, to='bnmc_project.Student_Registration'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='subjects',
            field=models.ManyToManyField(to='bnmc_project.ExamSubject'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Thana'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='year',
            field=models.ForeignKey(null=True, on_delete=None, to='bnmc_project.ExamYear'),
        ),
        migrations.AddField(
            model_name='centermanagement',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Exam'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='BalanceIncomes',
            field=models.ManyToManyField(blank=True, to='bnmc_project.BalanceIncome'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='TransfarRaffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.TransfarBalance'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='account',
            field=models.ForeignKey(on_delete=None, to='bnmc_project.Accounts'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='instituition',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Institution'),
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='student_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Student_Registration'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank_raffer',
            field=models.ForeignKey(on_delete=None, to='bnmc_project.Bank'),
        ),
        migrations.AddField(
            model_name='license_receive',
            name='renew_history',
            field=models.ManyToManyField(blank=True, to='bnmc_project.re_new_history', verbose_name='Renew History'),
        ),
    ]
