# Generated by Django 2.1.1 on 2019-01-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0008_auto_20190114_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationqualification',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='CGPA'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='session',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Session'),
        ),
    ]
