# Generated by Django 2.1.1 on 2019-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0009_auto_20190119_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bnmc_user',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
