# Generated by Django 2.1.1 on 2019-01-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0010_user_is_bnmc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_registrations',
            name='grade',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Upload photo'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='session',
            field=models.ForeignKey(max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Session'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='signature_first',
            field=models.ImageField(blank=True, null=True, upload_to='signature_student/', verbose_name='Upload photo'),
        ),
        migrations.AlterField(
            model_name='license_registrations',
            name='signature_sec',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='up photo'),
        ),
    ]
