# Generated by Django 2.1.1 on 2019-01-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0011_auto_20190124_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationqualification',
            name='education_type',
            field=models.CharField(choices=[('1', 'Science'), ('2', 'Comerce'), ('3', 'Arts'), ('4', 'Enginnering'), ('5', 'Nursing'), ('6', 'Doctorate'), ('7', 'Professional'), ('8', 'Technical')], max_length=120, verbose_name='Education Type'),
        ),
    ]
