# Generated by Django 2.1.1 on 2019-02-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0012_auto_20190130_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_file',
            name='student_file_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.StudentFileProgram'),
        ),
        migrations.AlterField(
            model_name='student_file',
            name='student_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Student_Registration'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='date_of_registration',
            field=models.DateField(blank=True, max_length=120, null=True, verbose_name='Date of Admission'),
        ),
        migrations.AlterField(
            model_name='studentfileprogram',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Program'),
        ),
    ]
