# Generated by Django 2.1.1 on 2019-05-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0017_examinationstudentregistration_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExamCenterManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_start', models.CharField(blank=True, max_length=300, null=True)),
                ('roll_end', models.CharField(blank=True, max_length=300, null=True)),
                ('center', models.ForeignKey(null=True, on_delete=None, to='bnmc_project.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='center',
            field=models.ForeignKey(null=True, on_delete=None, related_name='Center', to='bnmc_project.Institution'),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='end_role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='examinationstudentregistration',
            name='start_role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='final_exam',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalexamcentermanage',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Final_exam'),
        ),
    ]
