# Generated by Django 2.0.4 on 2019-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0019_auto_20190701_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='intuitionprofile',
            name='license_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intuitionprofile',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Designation'),
        ),
        migrations.AlterField(
            model_name='intuitionprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('1', 'Nurse'), ('2', 'Non-Nurse')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
