# Generated by Django 2.0.4 on 2019-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0020_auto_20190703_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intuitionprofile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='intuitionprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('1', 'Nurse'), ('2', 'Non-Nurse')], default=2, max_length=300, null=True),
        ),
    ]
