# Generated by Django 2.0.4 on 2019-07-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0021_auto_20190705_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intuitionprofile',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
