# Generated by Django 2.0.4 on 2019-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0022_auto_20190705_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intuitionprofile',
            name='work_starting_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
