# Generated by Django 2.0.4 on 2019-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0023_auto_20190705_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_working_place', models.CharField(blank=True, max_length=300, null=True)),
                ('current_position', models.CharField(blank=True, max_length=300, null=True)),
                ('Working_years_as_a_registered', models.CharField(blank=True, max_length=300, null=True)),
                ('Training', models.CharField(blank=True, max_length=300, null=True)),
                ('Attendance_in_Seminar', models.CharField(blank=True, max_length=300, null=True, verbose_name='Attendance in Seminar/ Symposium/Workshop/Case Presentation/ Meeting')),
                ('Research_skills', models.CharField(blank=True, max_length=300, null=True, verbose_name='Research Publications/ Other skills')),
            ],
        ),
    ]
