# Generated by Django 2.0.4 on 2019-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0024_applylicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylicense',
            name='Every_day',
            field=models.BooleanField(default=False, verbose_name='Every day I do my work through nursing care plan'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_always_try',
            field=models.BooleanField(default=False, verbose_name='I always try my best level to treat the patients equally in terms of race, religion, gender, age, nationality & economical class'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_always_wear_my_professional',
            field=models.BooleanField(default=False, verbose_name='I always wear my professional Uniform as approved by the Govt. of Bangladesh'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_am_aware',
            field=models.BooleanField(default=False, verbose_name='I am aware of  my  working area, delegated authority & responsibilities'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_am_aware_of_functions',
            field=models.BooleanField(default=False, verbose_name='I am aware of  functions of Bangladesh Nursing Council'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_am_aware_of_prescribed',
            field=models.BooleanField(default=False, verbose_name='I am aware of  prescribed code of conduct & ethics of Bangladesh Nursing Council'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_am_interested',
            field=models.BooleanField(default=False, verbose_name='I am interested  to act as a nurse teacher in my working situation'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_am_satisfied',
            field=models.BooleanField(default=False, verbose_name='I am satisfied with my Job'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_feel_the_present',
            field=models.BooleanField(default=False, verbose_name='I feel the present existing system of Registration & Renewal should be digitalized'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_feel_there_should_be',
            field=models.BooleanField(default=False, verbose_name='I feel there should be provision of examination system for Registration Renewal in Bangladesh like other countries'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_know_the_number',
            field=models.BooleanField(default=False, verbose_name='I know the  number of registered nurses, nursing institutions & colleges'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='I_own_my',
            field=models.BooleanField(default=False, verbose_name='I own my responsibility as one of the  Medical Team Members'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='In_Bangladesh_most',
            field=models.BooleanField(default=False, verbose_name='In Bangladesh most of the basic nursing activities are performed by patients’ attendance'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='before_starting',
            field=models.BooleanField(default=False, verbose_name='Before starting my work I exchange my greetings with the patients'),
        ),
        migrations.AddField(
            model_name='applylicense',
            name='license_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.license_receive'),
        ),
    ]
