# Generated by Django 2.0.4 on 2019-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0026_requestedprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedprogram',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
