# Generated by Django 2.0.4 on 2019-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0027_requestedprogram_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestedProgram',
            new_name='RequestedLicense',
        ),
        migrations.AlterField(
            model_name='applylicense',
            name='Working_years_as_a_registered',
            field=models.CharField(blank=True, choices=[('1', 'Nurse'), ('2', 'Midwife'), ('3', 'others')], max_length=300, null=True),
        ),
    ]
