# Generated by Django 2.0.4 on 2019-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0029_auto_20190710_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylicense',
            name='currently_working_place',
            field=models.CharField(blank=True, choices=[('1', 'Government'), ('2', 'Nongovernment')], max_length=300, null=True),
        ),
    ]
