# Generated by Django 2.0.4 on 2019-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0031_auto_20190727_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='applylicense',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
