# Generated by Django 2.0.4 on 2019-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0032_auto_20190730_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensehistory',
            name='renew_history',
        ),
        migrations.AddField(
            model_name='licensehistory',
            name='renew_history',
            field=models.ManyToManyField(blank=True, null=True, to='bnmc_project.re_new_history', verbose_name='Renew History'),
        ),
    ]
