# Generated by Django 2.0.4 on 2019-07-31 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0033_auto_20190731_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='re_new_history',
            name='image',
        ),
        migrations.AddField(
            model_name='re_new_history',
            name='license_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='re_new_history',
            name='program',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Program'),
        ),
        migrations.AlterField(
            model_name='licensehistory',
            name='registration_no',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Student id'),
        ),
        migrations.AlterField(
            model_name='licensehistory',
            name='renew_history',
            field=models.ManyToManyField(blank=True, to='bnmc_project.re_new_history', verbose_name='Renew History'),
        ),
    ]
