# Generated by Django 2.0.4 on 2019-08-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0035_license_receive_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_receive',
            name='same_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
