# Generated by Django 2.0.4 on 2019-08-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0036_auto_20190803_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
