# Generated by Django 2.0.4 on 2019-09-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0037_auto_20190804_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.District'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnmc_project.Thana'),
        ),
    ]
