# Generated by Django 2.0.4 on 2019-09-14 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnmc_project', '0038_auto_20190903_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_roll', models.CharField(blank=True, max_length=120, null=True)),
                ('end_roll', models.CharField(blank=True, max_length=120, null=True)),
                ('final_exam', models.ForeignKey(blank=True, null=True, on_delete=None, to='bnmc_project.Final_exam')),
                ('institutions', models.ManyToManyField(to='bnmc_project.Institution')),
                ('main_subjects', models.ManyToManyField(to='bnmc_project.ExamSubject')),
                ('sub_subjects', models.ManyToManyField(to='bnmc_project.SubSubject')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
